In [2]:
#Name:Priyanka Auti
#Roll No: 3302
#Batch: A
# Identify and Implement heuristic and search strategy for Travelling Salesperson Problem using nearest neighbour.

import numpy as np

ele= int(input("Give the number of cities:"))
print("Please write the elements of the matrix in a single line and separated by a space: ")

elements = list(map(int, input().split()))
dist_matrix = np.array(elements).reshape(ele, ele)

print(dist_matrix)


def nearest_neighbour(curr, unvisited,dist_matrix):
    nearest=9999
    neighbour= None
    for city in unvisited:
        if dist_matrix[curr][city]< nearest:
            nearest=dist_matrix[curr][city]
            neighbour= city
    return neighbour, nearest
def tsp_nn(dist_matrix):

    n=len(dist_matrix)
    tour=[0]*5
    unvisited=set(range(1,n))
    curr_city=0
    for i in range(1,n):
        next_city, dist = nearest_neighbour(curr_city, unvisited, dist_matrix)
        tour[i]=next_city
        curr_city= next_city
        unvisited.remove(next_city)
    tour[0]
    
    cost= sum(dist_matrix[tour[i]][tour[i+1]] for i in range(n-1))
    cost+= dist_matrix[tour[n-1]][tour[0]]
    return tour, cost
#dist_matrix=[
 #   [5,0,35,25],
#    [15,35,0,30],
  #  [4,25,30,0]
#]
tour, cost= tsp_nn(dist_matrix)
print("tour:", tour)
print("Total cost:" ,cost)

Give the number of cities:4
Please write the elements of the matrix in a single line and separated by a space: 
0 5 15 4 5 0 35 25 15 35 0 30 4 25 30 0
[[ 0  5 15  4]
 [ 5  0 35 25]
 [15 35  0 30]
 [ 4 25 30  0]]
tour: [0, 3, 1, 2, 0]
Total cost: 79
